config/routes.rb
Rails.application.routes.draw do

  resources :events
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks",confirmations: "confirmations"}
  match '/users/my_events' => 'events#my_index', via: [:get, :patch], :as => :my_events
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match 'user/:id/profile' => 'persons#profile', via: :get, :as => :user_profile
  root 'static_pages#home'

  match '/help', to: 'static_pages#help', via: 'get'
 match '/about', to: 'static_pages#about', via: 'get'

  get 'persons/profile', as: 'user_root'

end

app/models/event.rb
class Event < ActiveRecord::Base
  scope :is_public, -> { where(public: true)}
  belongs_to :user
  validates :name, presence: true,
            length: { maximum: 25 }
  validates :description, presence: true, length: {in: 10..100}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  require 'recurrence'
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /events
  # GET /events.json
  def index

    @events = Event.is_public
    @events_by_date_all=@events.group_by { |i| i.date_rem }
    @date= params[:date_rem] ? params[:date_rem].to_date : Date.today

    end
  def my_index
    @my_events=current_user.events.all
    @my_list_events=Array.new
    @my_events.each do |my_event|
      event_date=my_event.date_rem

      if my_event.everyday
        days = Recurrence.daily(:through => event_date.next_month)
        event_iter(days,@my_list_events,my_event)

        end

      if my_event.everyweek
        weeks=Recurrence.weekly(:on => event_date.wday,:start=>event_date,  :through=>event_date.next_year)
        event_iter(weeks,@my_list_events,my_event)
      end

      if my_event.everymonth
        months=Recurrence.monthly(:on => event_date.mday, :start=>event_date,:through=>event_date.next_year(2))
        event_iter(months,@my_list_events,my_event)

      end

      if my_event.everyyear
        years=Recurrence.yearly(:on=> [event_date.mon,event_date.mday])
        event_iter(years,@my_list_events,my_event)
      end




    end
    @my_list_events.uniq! { |uniq_event| [uniq_event.id, uniq_event.date_rem] }
    @events_by_date_my= @my_list_events.group_by {|j| j.date_rem}
    @date= (params[:date_rem] ? params[:date_rem] : Date.today).to_date

  end







  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params )
    puts @event
    @event.user=current_user
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Событие было удачно обновлено.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Событие было удачно удалено.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

  def event_iter(reccure,list,event)
    reccure.each do |my_reccure|
      event_curr=Event.find_or_initialize_by(id: event[:id],date_rem: event[:date_rem])
      event_curr.date_rem=my_reccure

      list<<event_curr




    end
end
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      po=params.require(:event).permit(:name, :description, :public, :everyday, :everyweek,:everymonth, :everyyear)
      po[:date_rem]=event_param_date
      puts po
      po
    end

    def event_param_date
      date_param=params.require(:event).permit(:date_rem)
      p= Date.parse( date_param.to_a.sort.collect{|c| c[1]}.join("-"))
      puts p
      p
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container-alba"><%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div class="alert-error">
      <h4><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h4>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Название %><br>
    <%= f.text_field :name,class: 'form-control input-lg' %>
  </div>
  <div class="field">
    <%= f.label :Описание_события %><br>
    <%= f.text_area :description, size: '10x20',class: 'form-control input-lg'%>
  </div>
  <div class="field">
    <%= f.label :Дата %><br>
    <%= f.date_select :date_rem%>
  </div>
    <div class="field">
  <%= f.check_box :public %>
  <%= f.label :Сделать_событие_публичным %>
    </div>

    <div class="field">
    <%= f.check_box :everyday %>
    <%= f.label :Повторять_событие_на_каждый_день %>
</div>
    <div class="field">
      <%= f.check_box :everyweek %>
      <%= f.label :Повторять_событие_на_каждую_неделю %>
    </div>
    <div class="field">
      <%= f.check_box :everymonth %>
      <%= f.label :Повторять_событие_на_каждый_месяц %>
    </div>

    <div class="field">
      <%= f.check_box :everyyear %>
      <%= f.label :Повторять_событие_на_каждый_год %>
    </div>
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/events/_title.html.erb
<h2 id="month">
  <%= link_to "<", date_rem: @date.prev_month%>
  <%= @date.strftime("%B %Y")%>
  <%= link_to ">", date_rem: @date.next_month %>
</h2>

app/views/events/edit.html.erb
<div class="container-alba">
  <h1>Редактировать событие</h1>

<%= render 'form' %>

<%= link_to 'Показать', @event,:class => 'btn btn-primary' %> |
<%= link_to 'Назад', events_path, :class => 'btn btn-primary' %>
</div>

app/views/events/index.html.erb
<div class="container-alba">
<h1>Список событий</h1>
</div>
  <div id="events">
    <%= render 'title' %>
    <%= calendar @date do |date_my|%>
      <%= date_my.day%>
        <% if @events_by_date_all[date_my]  %>
        <ul>
            <% @events_by_date_all[date_my].each do |event| %>
               <li><%= link_to event.name, event  %></li>
             <%end%>
                </ul>
    <%end%>
      <%end%>
</div>
<div class="container-alba">
<%= link_to 'Новое событие', new_event_path,:class => 'btn btn-primary' %>
</div>

app/views/events/my_index.html.erb
<div class="container-alba">
  <h1>Список событий</h1>
</div>
<div id="events">
  <%= render 'title' %>
  <%= calendar @date do |date_my|%>
      <%= date_my.day%>
      <% if @events_by_date_my[date_my]  %>
          <ul>
            <% @events_by_date_my[date_my].each do |event| %>
                <li><%= link_to event.name, event  %></li>
            <%end%>
          </ul>
      <%end%>
  <%end%>
</div>
<div class="container-alba">
<%= link_to 'Новое событие', new_event_path,:class => 'btn btn-primary'%>
</div>

app/views/events/new.html.erb
<div class="container-alba">
  <h1>Новое событие</h1>

<%= render 'form' %>

<%= link_to 'Назад', events_path %>
</div>

app/views/events/show.html.erb
<div class="container-alba"><p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Описание события:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Дата:</strong>
  <%= @event.date_rem %>
</p>
<p>
  <strong>Автор:</strong>
  <%= @event.user.first_name + " "+ @event.user.last_name %>
</p>
  <p>
    <strong>Статус:</strong>
    <%if (@event.public) %>
     <p>Публичный</p>
      <%else%>
      <p>Приватный</p>
      <%end%>
  </p>

<% if !(@event.public) %>
<%= link_to 'Редактировать', edit_event_path(@event) ,class: 'form-control input-lg'%>
      <%= link_to 'Назад', my_events_path,class: 'form-control input-lg' %>
  <%elsif (@event.public &&@event.user.email.eql?(current_user.email))%>
      <%= link_to 'Редактировать', edit_event_path(@event), class: 'form-control input-lg' %>
      <%= link_to 'Назад', events_path,class: 'form-control input-lg' %>

<%else%>

      <%= link_to 'Назад', events_path,class: 'form-control input-lg' %>
<%end%>


</div>