config/routes.rb
Rails.application.routes.draw do

  resources :events
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks",confirmations: "confirmations"}
  match '/users/my_events' => 'events#my_index', via: [:get, :patch], :as => :my_events
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match 'user/:id/profile' => 'persons#profile', via: :get, :as => :user_profile
  root 'static_pages#home'

  match '/help', to: 'static_pages#help', via: 'get'
 match '/about', to: 'static_pages#about', via: 'get'

  get 'persons/profile', as: 'user_root'

end

app/views/layouts/_footer.html.erb
<hr class="featurette-divider"><footer  class="container">
  <p>© 2015 Albatros, Inc. Все права защищены.</p>

</footer>
</hr>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
   <div class="navbar-header">
     <%= link_to "Calendar Albatros",  root_path, id: "logo", class: "navbar-brand"%>

   </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li><%=link_to "Главная", root_path%></li>
      <li><%=link_to "События", events_path%></li>
     <% if user_signed_in? {}%>
      <li><%=link_to "Профиль", user_profile_url(current_user.id)%></li>
      <li><%=link_to "Мои события", my_events_path%><li>
      <%end%>

    </ul>

    <ul class="nav navbar-nav  navbar-right" style="margin-right: 23px">


      <% if user_signed_in? %>

          <h5 style="color: #EFEFEF">Здравствуйте, <%= current_user.first_name+" "+current_user.last_name %></h5>
          <%= link_to '<button type="button" class="btn btn-primary">Выйти</button>'.html_safe,  destroy_user_session_path, :method => :delete %>

      <% else %>
          <%= link_to '<button type="button" class="btn btn-primary">Войти</button>'.html_safe, new_user_session_path %>
          <%= link_to '<button type="button" class="btn btn-primary">Регистрация</button>'.html_safe, new_user_registration_path %>

      <% end %>
    </ul>


</div>
    </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
<%=render 'layouts/header'%>

<%= yield %>


<%=render 'layouts/footer'%>

</body>
</html>